### ISSUE TITLE
Feature Recomendation - Add support for alfred-extra-pane/ Preview HTML panel

### ISSUE THREAD

**Issue by olivergiangvu** [zeitlings/alfred-unified-search#1]
Hi,

Thank you very much for such a nice workflow.

Just a small recommendation to ask support for this very nice HTML preview panel

https://github.com/mr-pennyworth/alfred-extra-pane

**Comment by zeitlings** [comment]
Hey @olivergiangvu
Thanks for the suggestion! I've integrated it into v1.1.0. 
Note the behaviour as detailed in the documentation - if you want the pane to be enabled all the time, you'll have to set the [environment variable](https://www.alfredapp.com/help/workflows/advanced/variables/#environment) `config_always_inject_quicklookurl` to `true`.
